# GitHub Actions Workflow for Docker CI
# Required Secrets:
# - DOCKER_USERNAME: Docker Hub 用户名，用于登录 Docker Hub
# - DOCKER_PASSWORD: Docker Hub 密码，用于登录 Docker Hub
# - DOCKER_IMAGE_URL: Docker 镜像的 URL，示例值：yourdomain.com/libraryname/imagename:tagname
# - PARAM_ARRAY: JSON 格式的参数数组，用于 -s 参数传递，示例值：["参数1", "参数2", "参数3"]
# - DOCKER_REGISTRY_URL
# - MINIO_ENDPOINT
# - MINIO_ACCESS_KEY
# - MINIO_SECRET_KEY

name: Docker CI with JSON Array

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: 检出代码
      - name: Check out the repository
        uses: actions/checkout@v2

      # Step 3: 登录 Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.DOCKER_REGISTRY_URL }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 4: 恢复 Docker 镜像缓存
      - name: Restore Docker image cache
        uses: actions/cache@v3
        with:
          path: /tmp/docker-image-cache
          key: ${{ runner.os }}-docker-image-${{ secrets.DOCKER_IMAGE_URL }}
          restore-keys: |
            ${{ runner.os }}-docker-image-

      # Step 5: 加载缓存的 Docker 镜像（如果存在）
      - name: Load Docker image from cache
        if: steps.restore.outputs.cache-hit == 'true'
        run: |
          docker load -i /tmp/docker-image-cache/cg-runner.tar || echo "No cached image found, pulling new image"

      # Step 6: 拉取并保存 Docker 镜像（如果没有缓存）
      - name: Pull and save Docker image
        run: |
          if [[ ! -f /tmp/docker-image-cache/cg-runner.tar ]]; then
            docker pull ${{ secrets.DOCKER_IMAGE_URL }}
            mkdir -p /tmp/docker-image-cache
            docker save ${{ secrets.DOCKER_IMAGE_URL }} -o /tmp/docker-image-cache/cg-runner.tar
          fi

      # Step 7: 解析 JSON 数组并循环运行容器
      - name: Run Docker container with JSON array
        env:
          PARAM_ARRAY: ${{ secrets.PARAM_ARRAY }}
        run: |
          # 使用 jq 解析 JSON 数组
          for param in $(echo "${PARAM_ARRAY}" | jq -r '.[]'); do
            echo "Running container with -s parameter: $param"
            docker run --rm --name cg-runner ${{ secrets.DOCKER_IMAGE_URL }} \
              java -jar /app/cg-runner.jar -s "$param"
          done

      # Step 7: 解析 JSON 数组并循环运行容器并重定向日志到独立文件
      - name: Run Docker container with JSON array and redirect logs to individual files
        env:
          PARAM_ARRAY: ${{ secrets.PARAM_ARRAY }}
        run: |
          for param in $(echo "${PARAM_ARRAY}" | jq -r '.[]'); do
            LOG_FILE="logs/docker_run_log_${param}.log"
            echo "Running container with -s parameter: $param" >> $LOG_FILE
            docker run --rm --name cg-runner ${{ secrets.DOCKER_IMAGE_URL }} \
              java -jar /app/cg-runner.jar -s "$param" >> $LOG_FILE 2>&1
          done

      - name: Minio Deploy
        uses: hkdobrev/minio-deploy-action@v1
        with:
          endpoint: ${{ secrets.MINIO_ENDPOINT }}
          access_key: ${{ secrets.MINIO_ACCESS_KEY }}
          secret_key: ${{ secrets.MINIO_SECRET_KEY }}
          bucket: 'cg-runner'  # Change this to your actual bucket name
          source_dir: 'logs'  # Assuming logs are in the current directory
          target_dir: ${{ steps.deploy.outputs.TARGET_DIR }}  # Use the generated target directory
